Repository code-wave-project/code-wave-FE, pull requests merged in 2025-02, with the labels that each got.

#6 [Feature] 대시보드 UI 구현
  .yarn/install-state.gz
  package.json
  src/App.tsx
  src/assets/icons/dashboard_menu_project.svg
  src/assets/icons/dashboard_menu_recent.svg
  src/assets/icons/icon_user.svg
  src/assets/icons/user_logout.svg
  src/assets/logos/logo_dashboard_side.svg
  src/components/Common/ActiveButton.style.ts
  src/components/Common/ActiveButton.tsx
  src/components/Common/Button.style.ts
  src/components/Common/Button.tsx
  src/components/Common/InputText.style.ts
  src/components/Common/InputText.tsx
  src/components/Dashboard/DashMenu.style.ts
  src/components/Dashboard/DashMenu.tsx
  src/components/Dashboard/DashSideBar.style.ts
  src/components/Dashboard/DashSideBar.tsx
  src/components/Dashboard/Header.style.ts
  src/components/Dashboard/Header.tsx
  src/components/Dashboard/ProjectCard.style.ts
  src/components/Dashboard/ProjectCard.tsx
  src/components/DashboardModal/CreateModModal.tsx
  src/components/DashboardModal/DeleteModModal.tsx
  src/components/DashboardModal/InviteModal.tsx
  src/components/DashboardModal/Modal.style.ts
  src/pages/Dashboard.tsx
  src/pages/Profile.tsx
  src/styles/pages/Dashboard.style.ts
  src/styles/pages/Profile.style.ts
  src/vite-env.d.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&Css

#8 [Feature] Toast 컴포넌트 UI 구현
  src/components/Common/ToastMessage.style.ts
  src/components/Common/ToastMessage.tsx
  src/components/Dashboard/ProjectCard.tsx
Labels: ✨ Feature, 🎨 Html&Css

#16 [Feature] 비밀번호 재설정 UI 구현
  src/pages/ResetPassword.tsx
Labels: ✨ Feature, 🎨 Html&Css

#15 [Feature] 아이디/비밀번호 찾기 UI 구현
  src/pages/FindAccount.tsx
Labels: ✨ Feature, 🎨 Html&Css

#14 [Feature] 회원 가입 UI 구현
  src/assets/icons/more.svg
  src/pages/SignUp.tsx
Labels: ✨ Feature, 🎨 Html&Css

#13 [Feature] 로그인 UI 구현
  src/pages/Login.tsx
Labels: ✨ Feature, 🎨 Html&Css

#18 [Feature] 대시보드 API 연동
  .yarn/install-state.gz
  README.md
  package.json
  src/App.tsx
  src/components/Common/InputText.tsx
  src/components/Common/ToastMessage.style.ts
  src/components/Dashboard/ProjectCard.style.ts
  src/components/Dashboard/ProjectCard.tsx
  src/components/DashboardModal/CreateModModal.tsx
  src/components/DashboardModal/DeleteModModal.tsx
  src/components/DashboardModal/Modal.style.ts
  src/components/IDE/Editor/AppBar/AppBar.tsx
  src/hooks/auth/useSignIn.ts
  src/hooks/common/useOnClickOutside.ts
  src/hooks/dashboard/useCheckProjects.ts
  src/hooks/dashboard/useDeleteProject.ts
  src/hooks/dashboard/useUpsertProject.ts
  src/lib/axios.ts
  src/pages/Dashboard.tsx
  src/pages/IDE.tsx
  src/pages/Login.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/pages/Dashboard.style.ts
  yarn.lock
Labels: 📬 API, ✨ Feature

#19 Feature/auth api
  src/components/IDE/Editor/AppBar/AppBar.tsx
  src/hooks/auth/useLogout.ts
  src/hooks/auth/useResetPassword.ts
  src/hooks/auth/useSignIn.ts
  src/hooks/file/useGetFiles.ts
  src/pages/Login.tsx
  src/types/api.ts
Labels: 📬 API

#22 [Feature] 에러 화면 UI 구현
  src/pages/ErrorNon.tsx
  src/pages/ErrorServer.tsx
  src/pages/Login.tsx
Labels: ✨ Feature, 🎨 Html&Css

#23 Api/ide api
  src/components/IDE/Editor/Editor.d.ts
  src/components/IDE/Editor/Editor.tsx
  src/components/IDE/Editor/TabBar/TabBar.d.ts
  src/components/IDE/Editor/TabBar/TabBar.styles.ts
  src/components/IDE/Editor/TabBar/TabBar.tsx
  src/components/IDE/SideBar/Panels/FileExplorer/CustomNode/CustomNode.styles.ts
  src/components/IDE/SideBar/Panels/FileExplorer/CustomNode/CustomNode.tsx
  src/components/IDE/SideBar/Panels/FileExplorer/FileExplorePanel.d.ts
  src/components/IDE/SideBar/Panels/FileExplorer/FileExplorePanel.tsx
  src/hooks/auth/useSignUp.ts
  src/hooks/dashboard/useCheckProjects.ts
  src/pages/SignUp.tsx
  src/store/collaboratorStore.ts
  src/store/fileStore.ts
  src/store/useFileStore.ts
  src/store/useTabStore.ts
  src/types/index.ts
Labels: 📬 API

#25 [Feature] 마이 페이지 UI 화면 구현
  src/pages/Profile.tsx
Labels: ✨ Feature, 🎨 Html&Css
